#!/usr/bin/env bash
set -euo pipefail

# Generates SHA-256 digest manifest for proving key material.
# Run after fetch-proving-data.sh to create src/offscreen/keyDigests.ts.
#
# Usage: ./scripts/generate-key-digests.sh

DIR="public/data/proving"
OUT="src/offscreen/keyDigests.ts"

if [ ! -d "$DIR" ]; then
  echo "ERROR: $DIR does not exist. Run scripts/fetch-proving-data.sh first."
  exit 1
fi

echo "Generating SHA-256 digests for proving key material..."

{
  echo "// Generated by scripts/generate-key-digests.sh — do not edit"
  echo "// Maps relative paths (under data/proving/) to SHA-256 hex digests"
  echo ""
  echo "export const KEY_DIGESTS: Record<string, string> = {"

  find "$DIR" -type f -not -name '.gitkeep' | sort | while read -r file; do
    rel="${file#"$DIR/"}"
    hash=$(shasum -a 256 "$file" | cut -d' ' -f1)
    echo "  '${rel}': '${hash}',"
  done

  echo "};"
} > "$OUT"

echo "Written to $OUT"
