// Generated by scripts/generate-key-digests.sh — do not edit
// Maps relative paths (under data/proving/) to SHA-256 hex digests

export const KEY_DIGESTS: Record<string, string> = {
  'benchmark-k10.preimage': '973e37eae13b79d875565c642175e5d2f80c345c2c44358eedd6e15335c3fc4d',
  'bls_midnight_2p10': '46b2290933cbed4c378889e4ba971f1a92888331ffb09466acd4ff61a1e2cb42',
  'bls_midnight_2p11': '9901589d7956ff58be0d85569b2f455b77b58c3758026ffb5bbe4807000b96d1',
  'bls_midnight_2p12': 'ef08eb3fcf62df8f72c515cffa027e681808b530cb016eea104115545ef6d5c8',
  'bls_midnight_2p13': 'd3324910969c4cc54143b8045b649e5c3a4bd5fb7b8f85fe1b770f640ce1c803',
  'bls_midnight_2p14': 'fc253016885ec830e97808c9ec920bb5cab5c21af590380a6cb5eb0538e2b244',
  'bls_midnight_2p15': '724c7c3d779148bb113c7ee9c034b2f27db16e6bdf315fde90105a9bad00b1de',
  'bls_midnight_2p16': '09c877216d6589b370263e18af40a030a901b41a7a7c37ef58c9901db41f05c6',
  'dust/9/spend.bzkir': '904181287e75b0fb596ba5fcc116c882ee5d28e3115304c93ebd913722ce5841',
  'dust/9/spend.prover': '996602da7ca386284e656c78ea03e55bffdba29475e6a67965c50de05e13efc2',
  'dust/9/spend.verifier': '3f1569ebcab0655c5c145b28947c74edc4e3f5c6b276e4404b661cf0905b49d3',
  'zswap/9/output.bzkir': '91dc8b401dd8385e8d29eaac018c70b578505f48c7952452ef319bc397fa1f1b',
  'zswap/9/output.prover': 'd992b04f13c3fd432f55fb8bfe6466d87bc181f1a2acf233ec228030bbdd4ed8',
  'zswap/9/output.verifier': '72e8074856f2f5c504ade25a86a2b8902c64aeb9497c4c8e6b26dea842a0ab08',
  'zswap/9/sign.bzkir': '37ea2094516e145a738126307cf92bd293f7cb524b1ccd49fa6f3225a9ec3a50',
  'zswap/9/sign.prover': 'fe7268dd2bdd107f862f881ac3c5bc71a6df77ce80bfed51cf71514648e660e0',
  'zswap/9/sign.verifier': 'e39a727caa0de167e6dd6122a9e3b758fecf48f9093ab77c0309648de8ce07e1',
  'zswap/9/spend.bzkir': '7cb5bbcf67cb212a3336fb439a77e8f32f0aa8a56185c8e1247d6cbfc7300205',
  'zswap/9/spend.prover': '19d234b5c68b7212ad6b0ec9334a95594748154128f3704eb576bcc843cc5c45',
  'zswap/9/spend.verifier': '544554effd7ae9fb9063be52a9ec2a986756301071fcd97bb4598fb45a335658',
};
